cat /etc/netplan/50-cloud-init.yaml 
network:
  version: 2
  ethernets:
    ens160:
      addresses:
        - 192.168.66.50/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
          - 192.168.66.1
        search: []
      routes:
        - to: "default"
          via: 192.168.66.1

    ens192:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
        use-dns: false
      routes:
        - to: 1.1.1.1
          via: 192.168.0.1
